### ISSUE TITLE
Comm 101

### ISSUE THREAD

**Issue by James-Lycett** [James-Lycett/workplace-wellness#88]
This is a space for communicating about communicating. James seems to have been dropped from chegg skills slack. I'm open to creating our own slack space, discord, or just plain texting or emailing - it's all the same to me. Github works fine too but not my preference since discussions are split in so many different places

**Comment by cozyfestiv** [comment]
Dang, ok that explains it. 

I literally messaged you recently, like "hope you're doing ok" but I meant, I hope you're still alive, lol 

I don't really want to text about it (I always try and keep my notifications to a minimum), and my email is always a disaster so I'd probably want to avoid those two. 

Creating a new slack channel would be my preference just because I use discord for all sorts of other nonsense and I ONLY associate slack with work, which I appreciate. But if we have trouble with it then discord is a good alternative.
